import { avatar, birthImg, birthImg2, idCard, idCardBack, signImg, video } from "./base64";

function MockData() {
  return {
    getAgreement: () => {
      return Promise.resolve(true);
    },
    resetCode: () => {
      return Promise.resolve(true);
    },
    verifyAgreement: () => {
      return Promise.resolve(true);
    },
    verifyCode: () => {
      return Promise.resolve(true);
    },
    login: () => {
      return Promise.resolve(true);
    },
    logout: () => {
      return Promise.resolve(true);
    },
    getInfo: () => {
      return Promise.resolve([
        {
          account_no: "0201058648602",
          branch_code: "000643",
          account_open_date: "1398/07/30",
          iban_number: "IR840530000000201058648602",
          account_owner_ship_type: "JN",
          account_description: "مهدي علي پوريان",
          ccy: "IRR",
          deposit_type: "S",
          deposit_type_description: "حساب پس انداز",
          ccy_description: "ريال ايران",
          account_owner_ship_type_description: "شخصي",
          account_account_status: "A",
          account_account_status_description: "فعال",
          account_type: "02",
          account_type_description: "سپرده سرمايه گذاري كوتاه مدت",
          branch_code_description: "شعبه بلوارناهيد",
          joint_type: "O",
          allowed: true,
          has_doc_record: false,
          valid_account: true,
          primary_account: true,
          customer_number: "0043739879",
          is_financial: true,
          is_non_financial: true,
          insert_by_branch_user: null,
          activation_account_status: null,
        },
      ]);
    },
    getUsersList: () => {
      return Promise.resolve([
        {
          id: 1,
          version: 0,
          identification_code: "999999999",
          employment_code: "1000500",
          username: "SYSTEM",
          firstname: "کاربر",
          lastname: "سیستم",
          is_enabled: false,
          is_locked: true,
          branch_code: "009000",
          branch_name: "اداره تمركز عمليات",
          roles: [],
        },
        {
          id: 21,
          last_modified_by: "admin",
          version: 2,
          identification_code: "000000000",
          employment_code: "0000000",
          username: "admin",
          firstname: "ادمین",
          lastname: "سیستم",
          is_enabled: true,
          is_locked: false,
          branch_code: "009000",
          branch_name: "اداره تمركز عمليات",
          roles: [],
        },
        {
          id: 2,
          last_modified_by: "admin",
          version: 2,
          identification_code: "000000001",
          employment_code: "0000001",
          username: "lili",
          firstname: "لیلا",
          lastname: "عبدالمالکی",
          is_enabled: true,
          is_locked: false,
          branch_code: "009000",
          branch_name: "اداره تمركز عمليات",
          roles: [],
        },
        {
          id: 3,
          last_modified_by: "admin",
          version: 2,
          identification_code: "000000002",
          employment_code: "0000002",
          username: "meh",
          firstname: "مهرداد",
          lastname: "کریمی",
          is_enabled: true,
          is_locked: false,
          branch_code: "009000",
          branch_name: "اداره تمركز عمليات",
          roles: [],
        },
        {
          id: 4,
          last_modified_by: "admin",
          version: 2,
          identification_code: "000000003",
          employment_code: "0000003",
          username: "ali",
          firstname: "علی",
          lastname: "حسین زاد",
          is_enabled: true,
          is_locked: false,
          branch_code: "009000",
          branch_name: "اداره تمركز عمليات",
          roles: [],
        },
      ]);
    },
    addNewCard: () => {
      return Promise.resolve([
        { account_no: "0201058648602", branch_code: "000643", account_open_date: "1398/07/30", iban_number: "IR840530000000201058648602" },
      ]);
    },
    getAllOpenAccount: () => {
      return Promise.resolve({
        data: [
          {
            id: 1001,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "REJECT",
            account_status_description: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1002,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "WAITING",
            account_status_description: "در انتظار تایید",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1003,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "REJECT",
            account_status_description: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1004,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "REJECT",
            account_status_description: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1005,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "WAITING",
            account_status_description: "در انتظار تایید",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1006,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "ACCEPT",
            account_status_description: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1007,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "ACCEPT",
            account_status_description: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1008,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "ACCEPT",
            account_status_description: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1009,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/07/24 09:19:45",
            account_status: "ACCEPT",
            account_status_description: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
        ],
      });
    },
    getAllAuthority: () => {
      return Promise.resolve({
        data: {
          end_row: 5,
          start_row: 0,
          total_rows: 5,
          data: [
            {
              id: 1,
              version: 0,
              authority_key: "Post:/api/bo/registration/define-username-password/v1",
              authority_description: "تعریف نام کاربری و رمزعبور مشتری در بک آفیس",
            },
            { id: 2, version: 0, authority_key: "Post:/api/bo/registration/v1", authority_description: "شروع فرآیند ثبت نام در بک آفیس" },
            { id: 3, version: 0, authority_key: "Post:/api/bo/users/v1", authority_description: "مدیریت کاربران" },
            { id: 4, version: 0, authority_key: "Post:/api/bo/customer-recovery/v1", authority_description: "بازیابی رمز یک مشتری" },
            { id: 5, version: 0, authority_key: "Post:/api/bo/edit-customer/v1", authority_description: "ویرایش اطلاعات مشتریان" },
          ],
        },
      });
    },
    getAllAuthorityGroup: () => {
      return Promise.resolve({
        data: [
          {
            id: 1,
            last_modified_by: "admin",
            version: 2,
            group_key: "REGISTRATION",
            group_description: "گروه ثبت\u200cنام",
            authorities: [
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
            ],
          },
          {
            id: 2,
            last_modified_by: "admin",
            version: 2,
            group_key: "REGISTRATION",
            group_description: "دسترسی ثبت\u200cنام",
            authorities: [
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
            ],
          },
          {
            id: 3,
            last_modified_by: "admin",
            version: 2,
            group_key: "REGISTRATION",
            group_description: "گروه دسترسی\u200cنام",
            authorities: [
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
            ],
          },
          {
            id: 4,
            last_modified_by: "admin",
            version: 2,
            group_key: "REGISTRATION",
            group_description: "گروه دسترسی ثبت",
            authorities: [
              {
                authority_keys: "Post:/api/bo/registration/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
              {
                authority_keys: "Post:/api/bo/registration/define-username-password/v1",
                authority_description: "کاربری و رمزعبور مشتری در بک آفیس",
              },
            ],
          },
        ],
      });
    },

    getAllUsers: () => {
      return Promise.resolve({
        data: {
          data: [
            {
              id: 3,
              last_modified_by: "mehrdad",
              version: 16,
              identification_code: "000000002",
              employment_code: "0000002",
              username: "mehrdad",
              firstname: "مهرداد",
              lastname: "کریمی",
              is_enabled: true,
              is_locked: false,
              branch_code: "009000",
              branch_name: "اداره تمركز عمليات",
              gender: "MALE",
              roles: [],
            },
          ],
        },
      });
    },
    getUploadedFiles: (params) => {
      let file = {};
      if (params.type === "ID_CARD_PHOTO") {
        file = { file: avatar };
      } else if (params.type === "ID_CARD") {
        file = { file: idCard };
      } else if (params.type === "ID_CARD_BACK") {
        file = { file: idCardBack };
      } else if (params.type === "BIRTH_CERTIFICATE_P_1") {
        file = { file: birthImg };
      } else if (params.type === "BIRTH_CERTIFICATE_P_DESC") {
        file = { file: birthImg2 };
      } else if (params.type === "SIGN") {
        file = { file: signImg };
      } else if (params.type === "VIDEO") {
        file = { file: video };
      }
      return Promise.resolve(file);
    },
    getUploadedFilesRegisterForget: (params) => {
      let file = {};
      if (params.type === "ID_CARD_PHOTO") {
        file = { file: avatar };
      } else if (params.type === "ID_CARD") {
        file = { file: idCard };
      } else if (params.type === "VIDEO") {
        file = { file: video, video_expression: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند." };
      }
      return Promise.resolve(file);
    },
    confirmOpeningAccount: (payload) => {
      return Promise.resolve(true);
    },
    getRegisterAndForget: () => {
      return Promise.resolve({
        data: [
          {
            id: 1001,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "REJECT",
            verify_offline_auth_desc: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1002,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "WAITING",
            verify_offline_auth_desc: "در انتظار تایید",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1003,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "REJECT",
            verify_offline_auth_desc: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1004,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "FORGET",
            event_desc: "فراموشی",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "REJECT",
            verify_offline_auth_desc: "رد شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1005,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "WAITING",
            verify_offline_auth_desc: "در انتظار تایید",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1006,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "FORGET",
            event_desc: "فراموشی",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "ACCEPT",
            verify_offline_auth_desc: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1007,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "ACCEPT",
            verify_offline_auth_desc: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1008,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "FORGET",
            event_desc: "فراموشی",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "ACCEPT",
            verify_offline_auth_desc: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
          {
            id: 1009,
            last_modified_by: "anonymous user",
            version: 28,
            reference_number: "DP231178994443",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "0064711481",
            event: "INSTALL",
            event_desc: "ثبت نام",
            created_date: "1401/07/24 09:19:45",
            verify_offline_auth: "ACCEPT",
            verify_offline_auth_desc: "تایید شده",
            full_name: "Test name Test family",
            status: "ERROR",
            mobile: "09123456786",
            text: "خنده و شادمانی بهترین نیایش جهان هستی است و نزدیکترین راه بسوی خداوند.",
          },
        ],
      });
    },
    confirmRegisterForget: () => {
      return Promise.resolve(true);
    },
    getCurrentUser: () => {
      return Promise.resolve({ data: { firstname: "علی", lastname: "حسین زاد" } });
    },
    getAllRoles: () => {
      return Promise.resolve(true);
    },
    getAllHistoryOpenAccount: () => {
      return Promise.resolve({
        end_row: 1,
        start_row: 0,
        total_rows: 1,
        data: [
          {
            id: 481,
            version: 0,
            reference_number: "DP239373732353",
            firstname: "Test name",
            lastname: "Test family",
            identification_code: "3720340147",
            mobile_number: "09185972640",
            video_expression: "ترس هایی را که با آنها مواجه نمیشویم تبدیل به محدودیت های ما میشوند",
            event: "CREATE_ACCOUNT",
            event_description: "افتتاح حساب",
            created_date: "1401/08/17 23:59:59",
            account_status: null,
            account_creation_status: null,
            status: "ERROR",
            error_desc: "خطا در تعریف مشتری هنگام افتتاح حساب",
            fullname: null,
          },
        ],
      });
    },
    getAccountsList: () => {
      return Promise.resolve({
        data: {
          stamp_owner_identification_code: "0065150430",
          stamp_owner_name: null,
          leader_identification_code: "0065150430",
          leader_name: null,
          is_active_corporate_customer: false,
          is_corporate_customer: true,
          client_account_dto_list: [
            {
              account_no: "0101203877602",
              branch_code: "0168",
              account_open_date: "1399/10/24",
              iban_number: "IR240530000000101203877602",
              account_owner_ship_type: "AS",
              account_description: " توسعه نرم افزارهاي بانكي نگاه فرداي كارآفرين",
              ccy: "IRR",
              deposit_type: "CA",
              deposit_type_description: "پس انداز جاری",
              ccy_description: "ريال",
              account_owner_ship_type_description: "شرکتی",
              account_status: "A",
              account_status_description: "فعال",
              account_type: "1121",
              account_type_description: "قرض الحسنه جاري ريالي - حقوقي انفرادي - عادي",
              branch_code_description: "",
              joint_type: null,
              allowed: true,
              has_doc_record: true,
              valid_account: true,
              primary_account: true,
              customer_number: "44246307",
              is_financial: true,
              is_non_financial: true,
              insert_by_branch_user: null,
              activation_status: true,
              follow_code: "2001599568176033",
            },
            {
              account_no: "0201205799600",
              branch_code: "0168",
              account_open_date: "1399/10/29",
              iban_number: "IR700530000000201205799600",
              account_owner_ship_type: "AS",
              account_description: " توسعه نرم افزارهاي بانكي نگاه فرداي كارآفرين",
              ccy: "IRR",
              deposit_type: "SSDA",
              deposit_type_description: "سرمایه گذاری کوتاه مدت",
              ccy_description: "ريال",
              account_owner_ship_type_description: "شرکتی",
              account_status: "A",
              account_status_description: "فعال",
              account_type: "3201",
              account_type_description: "سپرده سرمايه گذاري كوتاه مدت - حقوقي انفرادي عادي",
              branch_code_description: "",
              joint_type: null,
              allowed: true,
              has_doc_record: false,
              valid_account: true,
              primary_account: true,
              customer_number: "44246307",
              is_financial: true,
              is_non_financial: true,
              insert_by_branch_user: null,
              activation_status: true,
              follow_code: "2001600448238478",
            },
            {
              account_no: "1901501051600",
              branch_code: "0643",
              account_open_date: "1401/09/09",
              iban_number: "IR650530000001901501051600",
              account_owner_ship_type: "AS",
              account_description: " توسعه نرم افزارهاي بانكي نگاه فرداي كارآفرين",
              ccy: "IRR",
              deposit_type: "SA",
              deposit_type_description: "قرض الحسنه پس انداز",
              ccy_description: "ريال",
              account_owner_ship_type_description: "شرکتی",
              account_status: "A",
              account_status_description: "فعال",
              account_type: "1123",
              account_type_description: "قرض الحسنه جاري فاقد دسته چك کد19(آفرين) - حقوقي انفرادي",
              branch_code_description: "",
              joint_type: null,
              allowed: true,
              has_doc_record: false,
              valid_account: true,
              primary_account: true,
              customer_number: "44246307",
              is_financial: true,
              is_non_financial: true,
              insert_by_branch_user: null,
              activation_status: true,
              follow_code: "2001701966524015",
            },
          ],
        },
      });
    },
    getCardsList: () => {
      return Promise.resolve({
        data: {
          end_row: 10,
          start_row: 0,
          total_rows: 34782,
          data: [
            {
              reference_number: "DP463709336064",
              identification_code: "5910178288",
              firstname: "بهنام",
              lastname: "مهرو",
              mobile_number: "09044307408",
              receive_date: null,
              operation_status: "LOGICALLY_ISSUED",
              receive_status_description: "ارسال به مشتری",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282501",
              account_number: "2101923298607",
              iban: "IR810530000002101923298607",
              address: "استان تهران، شهر شمیرانات، اراج، خیابان بدیعی، خیابان شهید برادران موحددانش، پلاک -32، طبقه 1",
              postal_code: "1957963851",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "10:48:08 1403/05/13",
              physical_issued_date: "10:48:08 1403/05/14",
            },
            {
              reference_number: "DP463703306752",
              identification_code: "2250080003",
              firstname: "آناهيتا",
              lastname: "اصغري",
              mobile_number: "09384667643",
              receive_date: null,
              operation_status: "LOGICALLY_ISSUED",
              receive_status_description: "ارسال به مشتری",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282378",
              account_number: "2101923204600",
              iban: "IR710530000002101923204600",
              address: "استان تهران، شهر تهران، عباس آباد-اندیشه، خیابان یکم، خیابان کوه نور، پلاک 4، طبقه همکف",
              postal_code: "1587616813",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "10:23:37 1403/05/13",
              physical_issued_date: "10:23:37 1403/05/14",
            },
            {
              reference_number: "DP463701557760",
              identification_code: "4900788295",
              firstname: "علي",
              lastname: "باقري",
              mobile_number: "09399800932",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282337",
              account_number: "2101923175607",
              iban: "IR920530000002101923175607",
              address: "استان تهران، شهر ملارد، محله، کوچه ((نرگس))، کوچه نسترن، پلاک -16، ساختمان الماس، طبقه 1، واحد 1",
              postal_code: "3176185415",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "10:16:29 1403/05/13",
              physical_issued_date: "10:16:29 1403/05/14",
            },
            {
              reference_number: "DP463697814017",
              identification_code: "0590274554",
              firstname: "زهرا",
              lastname: "طاهري",
              mobile_number: "09022516313",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282279",
              account_number: "3101923134602",
              iban: "IR770530000003101923134602",
              address: "استان تهران، شهر تهران، تیموری، خیابان شهید داود حبیب زادگان، بن بست فاطمی، پلاک 1، طبقه 5، واحد 13",
              postal_code: "1459996491",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "10:01:16 1403/05/13",
              physical_issued_date: "10:01:16 1403/05/14",
            },
            {
              reference_number: "DP463697203712",
              identification_code: "2281637735",
              firstname: "زهرا",
              lastname: "رضائي",
              mobile_number: "09367151929",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282261",
              account_number: "2101923132607",
              iban: "IR020530000002101923132607",
              address:
                "استان البرز، شهر کرج، رجائی شهرفازدو، خیابان دکترسیدمحمود حسابی، خیابان شهیدمسعود پورصومعه [نهم غربی]، پلاک 55، طبقه 3، واحد 10",
              postal_code: "3148965739",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "09:58:48 1403/05/13",
              physical_issued_date: "09:58:48 1403/05/14",
            },
            {
              reference_number: "DP463683183104",
              identification_code: "0070888795",
              firstname: "اميرحسين",
              lastname: "معماريان پور",
              mobile_number: "09123790121",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700292187",
              account_number: "3101923010600",
              iban: "IR790530000003101923010600",
              address:
                "استان تهران، شهر شمیرانات، شهرک مخابرات، بلوار امیرسرلشگرخلبان محمد حق شناس، خیابان کوهیار، پلاک 0، ساختمان بوستان 1، طبقه 4، واحد 43",
              postal_code: "1981981993",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "09:01:43 1403/05/13",
              physical_issued_date: "09:01:43 1403/05/14",
            },
            {
              reference_number: "DP463682093569",
              identification_code: "2592366288",
              firstname: "رامين",
              lastname: "درگاهي گيلوائي",
              mobile_number: "09127175302",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700292179",
              account_number: "2101923022604",
              iban: "IR400530000002101923022604",
              address: "استان تهران، شهر تهران، حسن آباد - زرگنده، خیابان شهیدعلی اصغرگوی آبادی، خیابان شهیدمحمد علی راجیان، پلاک 0، طبقه همکف",
              postal_code: "1916717617",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "08:57:18 1403/05/13",
            },
            {
              reference_number: "DP463679050241",
              identification_code: "1920298657",
              firstname: "محمدمهدي",
              lastname: "صرفه جو",
              mobile_number: "09384907305",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282253",
              account_number: "3101923060605",
              iban: "IR870530000003101923060605",
              address: "استان تهران، شهر تهران، گرگان، خیابان شهید سرتیپ نامجو، کوچه شهید مرتضی تیموری، پلاک 7، طبقه 5، واحد شمالی",
              postal_code: "1614775810",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "08:44:55 1403/05/13",
            },
            {
              reference_number: "DP463674675713",
              identification_code: "1450794750",
              firstname: "ميلاد",
              lastname: "فرزانه تولون",
              mobile_number: "09118860870",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700292161",
              account_number: "2101922937602",
              iban: "IR740530000002101922937602",
              address: "استان اردبیل، شهر اردبیل، ججین، کوچه شفق17، خیابان خیرین مدرسه ساز، پلاک 0، طبقه 1",
              postal_code: "5619759419",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "08:27:07 1403/05/13",
            },
            {
              reference_number: "DP463654687232",
              identification_code: "0012233153",
              firstname: "سعيد",
              lastname: "بصيري",
              mobile_number: "09124895316",
              receive_date: null,
              operation_status: "SENT",
              receive_status_description: "در انتظار تایید",
              card_operation: "ISSUE_NEW",
              card_operation_description: "صدور جدید",
              pan: "6274881700282246",
              account_number: "2101922848603",
              iban: "IR660530000002101922848603",
              address:
                "استان تهران، شهر تهران، تهرانپارس، خیابان شهید برادران مظفری (127)، خیابان شهید عبدالحسین قمی (218شرقی)، پلاک 42، طبقه 2، واحد 8",
              postal_code: "1655764875",
              card_color: "50AF47",
              from_account_creation: true,
              created_date: "07:05:46 1403/05/13",
            },
          ],
        },
      });
    },
  };
}
export default MockData();
